version: "3"

services:
  server-todo-node:
    container_name: server-todo-node
    restart: unless-stopped
    working_dir: /usr/src/app
    build:
      context: .
    env_file: .env
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    expose:
      - ${PORT}
    ports:
      - "${PORT}:${PORT}/tcp"
      - "${INSPECT_PORT}:${INSPECT_PORT}"
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "run", "watch"]
    networks:
      - default

  mongo-todo-node:
    container_name: mongo-todo-node
    image: "mongo:4.2.6"
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_DATA_DIR=/mongo-data
      - MONGO_LOG_DIR=/dev/null
    command: mongod
    networks:
      - default

volumes:
  mongo-data:
